name: Test

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Run Node install and build
        run: |
          npm ci
          npm run build
